#!/usr/bin/env python3
"""
Sends the personalized vendor emails generated by generate.py via Resend.

Usage:
  python3 send.py --dry-run
  python3 send.py --test thek2way17@gmail.com
  python3 send.py
  python3 send.py --only-group A
  python3 send.py --no-bcc

By default sends to every recipient with BCC to chef@trainercenter.com,
rate-limited to ~2/sec (Resend free tier limit).

# RESEND_API_KEY — where this key lives
The RESEND_API_KEY for Trainer Center HB is the same key used by the
`send-vendor-email` Supabase Edge Function. It is stored in three places,
all kept in sync:
  1. Supabase secret `RESEND_API_KEY` in project tfneuzbhiqsdvnhhdfsw
       supabase secrets set RESEND_API_KEY=... --project-ref tfneuzbhiqsdvnhhdfsw
  2. Netlify env var `RESEND_API_KEY` on the trainercenter site (all contexts)
       netlify env:set RESEND_API_KEY ...
  3. Local `~/Apps/trainercenter/.env` (gitignored — local dev/scripting only)

This script auto-reads from `~/Apps/trainercenter/.env` if the env var is
not already set. Verified sending domain is `mysendz.com`; from-address is
"Trainer Center HB <noreply@mysendz.com>".
"""

import os, sys, time, json, urllib.request, urllib.error, argparse, re

def load_env_from_file(path):
    """Cheap dotenv loader — reads KEY=VALUE lines, ignores comments/blanks."""
    if not os.path.isfile(path):
        return
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            key, val = line.split('=', 1)
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val

# Auto-load from ~/Apps/trainercenter/.env so callers don't have to pass the key
load_env_from_file(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '.env'))

DRAFTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'drafts')
FROM_ADDRESS = 'Trainer Center HB <noreply@mysendz.com>'
BCC = 'chef@trainercenter.com'
REPLY_TO = 'Trainercenter.pokemon@gmail.com'
RATE_LIMIT_DELAY = 0.55  # ~1.8 req/sec, safely under Resend's 2/sec

# Single source of truth — pull vendor list + subjects from generate.py
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generate import VENDORS, SUBJECTS  # noqa: E402


def slug(v):
    return f"{v['first']}-{v['last']}".lower().replace(' ', '-').replace('--', '-')


def html_to_text(html):
    """Cheap HTML → text fallback for the text/plain part of each email."""
    text = re.sub(r'<style[^>]*>.*?</style>', '', html, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r'<head[^>]*>.*?</head>', '', text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r'<br\s*/?>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'</p>', '\n\n', text, flags=re.IGNORECASE)
    text = re.sub(r'</li>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'<[^>]+>', '', text)
    text = re.sub(r'&nbsp;', ' ', text)
    text = re.sub(r'&amp;', '&', text)
    text = re.sub(r'&lt;', '<', text)
    text = re.sub(r'&gt;', '>', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def send_one(api_key, to, subject, html_body, bcc=None, reply_to=None, dry_run=False):
    text_body = html_to_text(html_body)
    payload = {
        'from': FROM_ADDRESS,
        'to': [to],
        'subject': subject,
        'html': html_body,
        'text': text_body,
    }
    if bcc:
        payload['bcc'] = [bcc]
    if reply_to:
        payload['reply_to'] = reply_to

    if dry_run:
        print(f"  [DRY-RUN] {to:40s} subj={subject[:60]!r}")
        return True

    req = urllib.request.Request(
        'https://api.resend.com/emails',
        method='POST',
        headers={
            'Authorization': f'Bearer {api_key}',
            'Content-Type': 'application/json',
            'User-Agent': 'TrainerCenterHB-VendorMailer/1.0',
            'Accept': 'application/json',
        },
        data=json.dumps(payload).encode('utf-8'),
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
            return data.get('id') or True
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='ignore')[:300]
        print(f"  ❌ HTTP {e.code} for {to}: {body}")
        return False
    except Exception as e:
        print(f"  ❌ {type(e).__name__} for {to}: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description='Send vendor emails via Resend')
    parser.add_argument('--dry-run', action='store_true', help='Print recipients without sending')
    parser.add_argument('--test', metavar='EMAIL', help='Send one email per group to this address (4 emails total)')
    parser.add_argument('--only-group', metavar='G', choices=['A', 'B', 'C', 'D'], help='Send only to this group')
    parser.add_argument('--no-bcc', action='store_true', help='Skip BCC to chef@trainercenter.com')
    args = parser.parse_args()

    api_key = os.environ.get('RESEND_API_KEY', '').strip()
    if not args.dry_run and not api_key:
        print("ERROR: RESEND_API_KEY not set. Pass it like:")
        print("  RESEND_API_KEY=re_xxx python3 send.py")
        sys.exit(1)

    bcc = None if args.no_bcc else BCC

    # Build the work queue
    work = []
    if args.test:
        # One email per group, all sent to the test address
        seen_groups = set()
        for v in VENDORS:
            if v['group'] in seen_groups:
                continue
            seen_groups.add(v['group'])
            work.append({**v, 'override_email': args.test})
            if len(seen_groups) == 4:
                break
    else:
        for v in VENDORS:
            if args.only_group and v['group'] != args.only_group:
                continue
            work.append(v)

    print(f"\n{'═' * 60}")
    print(f"Mode: {'DRY-RUN' if args.dry_run else ('TEST → ' + args.test if args.test else 'LIVE SEND')}")
    print(f"From: {FROM_ADDRESS}")
    print(f"BCC:  {bcc or '(none)'}")
    print(f"Reply-to: {REPLY_TO}")
    print(f"Recipients: {len(work)}")
    print(f"{'═' * 60}\n")

    if not args.dry_run and not args.test:
        # Final confirm before live blast
        confirm = input(f"About to send {len(work)} live emails. Type 'send' to confirm: ").strip()
        if confirm.lower() != 'send':
            print("Cancelled.")
            return

    sent_ok = 0
    failed = []

    for i, v in enumerate(work):
        recipient = v.get('override_email', v['email'])
        path = os.path.join(DRAFTS_DIR, f"group-{v['group']}", f"{slug(v)}.html")
        if not os.path.isfile(path):
            print(f"  ❌ MISSING DRAFT: {path}")
            failed.append((recipient, 'missing draft'))
            continue
        with open(path) as f:
            html_body = f.read()
        subject = SUBJECTS[v['group']]

        result = send_one(api_key, recipient, subject, html_body, bcc=bcc, reply_to=REPLY_TO, dry_run=args.dry_run)
        if result:
            sent_ok += 1
            if not args.dry_run:
                msg_id = result if isinstance(result, str) else 'ok'
                print(f"  ✓ [{v['group']}] {recipient:40s} {msg_id}")
        else:
            failed.append((recipient, 'send failed'))

        # Rate limit (skip on last)
        if i < len(work) - 1 and not args.dry_run:
            time.sleep(RATE_LIMIT_DELAY)

    print(f"\n{'═' * 60}")
    print(f"Sent: {sent_ok} / {len(work)}")
    if failed:
        print(f"Failed: {len(failed)}")
        for email, reason in failed:
            print(f"  - {email}: {reason}")
    print(f"{'═' * 60}\n")


if __name__ == '__main__':
    main()
