// Auto-generated grading candidates (100 cards, $500+ PSA10). Source: CardChase pricing pipeline.
// Prices: NM/PSA9/PSA10 = median consensus (Countdown + Poketrace + PriceCharting). suspect=true means raw NM looks like a bad match.
export const GRADING_CARDS = [
  {
    "name": "Charizard GX",
    "set": "Burning Shadows",
    "number": "150",
    "era": "XYSM",
    "tier": "premium",
    "gem": "tough",
    "why": "'First rainbow Zard', deep buyer pool, strong multiplier",
    "rawNM": 420,
    "psa9": 752,
    "psa10": 6600,
    "mult": 15.7,
    "suspect": false
  },
  {
    "name": "Umbreon ex",
    "set": "Prismatic Evolutions",
    "number": "161",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "#1 modern chase. Eeveelution demand; even PSA9 ~$1500. Textured SIR, screen centering",
    "rawNM": 1450,
    "psa9": 1636,
    "psa10": 6149,
    "mult": 4.2,
    "suspect": false
  },
  {
    "name": "Reshiram ex",
    "set": "White Flare",
    "number": "174/86",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $5,107 (2025)",
    "rawNM": 330,
    "psa9": 362,
    "psa10": 773,
    "mult": 2.3,
    "suspect": false
  },
  {
    "name": "Gardevoir ex",
    "set": "Generations",
    "number": "RC30",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $5,000 (2016)",
    "rawNM": 70,
    "psa9": 199,
    "psa10": 2611,
    "mult": 37.3,
    "suspect": false
  },
  {
    "name": "Umbreon VMAX",
    "set": "Evolving Skies",
    "number": "215/203",
    "era": "SwSh",
    "tier": "premium",
    "gem": "tough",
    "why": "'Moonbreon', hobby #1 chase. Notorious centering, only submit dead-center",
    "rawNM": 1998,
    "psa9": 2247,
    "psa10": 4600,
    "mult": 2.3,
    "suspect": false
  },
  {
    "name": "Alakazam ex",
    "set": "Fates Collide",
    "number": "125",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $4,183 (None)",
    "rawNM": 120,
    "psa9": 470,
    "psa10": 3738,
    "mult": 31.2,
    "suspect": false
  },
  {
    "name": "Pikachu ex",
    "set": "Ascended Heroes",
    "number": "276/217",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $4,750 (None)",
    "rawNM": 1224,
    "psa9": 1200,
    "psa10": 3650,
    "mult": 3.0,
    "suspect": false
  },
  {
    "name": "Mew ex",
    "set": "Paldean Fates",
    "number": "232",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $4,000 (2024)",
    "rawNM": 893,
    "psa9": 981,
    "psa10": 3708,
    "mult": 4.2,
    "suspect": false
  },
  {
    "name": "Gyarados ex",
    "set": "BREAKpoint",
    "number": "123/122",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $3,400 (None)",
    "rawNM": 156,
    "psa9": 430,
    "psa10": 2996,
    "mult": 19.2,
    "suspect": false
  },
  {
    "name": "Mega Charizard X ex",
    "set": "Phantasmal Flames",
    "number": "130/94",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,650 (None)",
    "rawNM": 342,
    "psa9": 416,
    "psa10": 2976,
    "mult": 8.7,
    "suspect": false
  },
  {
    "name": "Giratina V",
    "set": "Lost Origin",
    "number": "186/196",
    "era": "SwSh",
    "tier": "premium",
    "gem": "tough",
    "why": "Top-3 SwSh alt art, elite liquidity, dark surface scrutiny",
    "rawNM": 700,
    "psa9": 900,
    "psa10": 3126,
    "mult": 4.5,
    "suspect": false
  },
  {
    "name": "Mega Gengar ex",
    "set": "Ascended Heroes",
    "number": "284/217",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $3,300 (2026)",
    "rawNM": 1301,
    "psa9": 1275,
    "psa10": 3085,
    "mult": 2.4,
    "suspect": false
  },
  {
    "name": "Rayquaza VMAX",
    "set": "Evolving Skies",
    "number": "218",
    "era": "SwSh",
    "tier": "premium",
    "gem": "tough",
    "why": "Iconic alt art, holo scratch risk, deep demand",
    "rawNM": 993,
    "psa9": 1165,
    "psa10": 2850,
    "mult": 2.9,
    "suspect": false
  },
  {
    "name": "Gengar VMAX",
    "set": "Fusion Strike",
    "number": "271/264",
    "era": "SwSh",
    "tier": "premium",
    "gem": "TRAP",
    "why": "Black bg shows every scratch, sub-20% gem. Big multiplier, high risk",
    "rawNM": 897,
    "psa9": 974,
    "psa10": 2650,
    "mult": 3.0,
    "suspect": false
  },
  {
    "name": "Mega Charizard X ex",
    "set": "Phantasmal Flames",
    "number": "125",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Mega SIR, top Phantasmal Flames chase, Charizard liquidity",
    "rawNM": 901,
    "psa9": 899,
    "psa10": 2436,
    "mult": 2.7,
    "suspect": false
  },
  {
    "name": "Mega Dragonite ex",
    "set": "Ascended Heroes",
    "number": "290/217",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $2,200 (2026)",
    "rawNM": 863,
    "psa9": 815,
    "psa10": 2204,
    "mult": 2.6,
    "suspect": false
  },
  {
    "name": "Sylveon ex",
    "set": "Generations",
    "number": "RC21",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $2,200 (2016)",
    "rawNM": 77,
    "psa9": 184,
    "psa10": 2200,
    "mult": 28.7,
    "suspect": false
  },
  {
    "name": "Gardevoir ex",
    "set": "Steam Siege",
    "number": "116",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $2,000 (2016)",
    "rawNM": 88,
    "psa9": 193,
    "psa10": 1457,
    "mult": 16.6,
    "suspect": false
  },
  {
    "name": "Zekrom ex",
    "set": "Black Bolt",
    "number": "172",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,925 (None)",
    "rawNM": 532,
    "psa9": 547,
    "psa10": 1743,
    "mult": 3.3,
    "suspect": false
  },
  {
    "name": "Charizard GX",
    "set": "Hidden Fates",
    "number": "SV49",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,850 (2019)",
    "rawNM": 546,
    "psa9": 655,
    "psa10": 1749,
    "mult": 3.2,
    "suspect": false
  },
  {
    "name": "Charizard ex",
    "set": "Pokemon 151",
    "number": "199",
    "era": "SV",
    "tier": "premium",
    "gem": "TRAP",
    "why": "Huge demand but ~28% gem (centering nightmare). Only grade dead-center copies",
    "rawNM": 405,
    "psa9": 440,
    "psa10": 1675,
    "mult": 4.1,
    "suspect": false
  },
  {
    "name": "Mewtwo",
    "set": "Hidden Fates",
    "number": "SM214",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $700 (2023)",
    "rawNM": 9,
    "psa9": 52,
    "psa10": 950,
    "mult": 105.1,
    "suspect": true
  },
  {
    "name": "Sylveon ex",
    "set": "Prismatic Evolutions",
    "number": "156",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Eeveelution halo, 2nd behind Umbreon",
    "rawNM": 406,
    "psa9": 432,
    "psa10": 1700,
    "mult": 4.2,
    "suspect": false
  },
  {
    "name": "Lugia V",
    "set": "Silver Tempest",
    "number": "186/195",
    "era": "SwSh",
    "tier": "premium",
    "gem": "moderate",
    "why": "Silver Tempest hero card, big multiplier off mid raw",
    "rawNM": 488,
    "psa9": 573,
    "psa10": 1500,
    "mult": 3.1,
    "suspect": false
  },
  {
    "name": "Pikachu ex",
    "set": "Ascended Heroes",
    "number": "277",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,400 (2026)",
    "rawNM": 509,
    "psa9": 525,
    "psa10": 1650,
    "mult": 3.2,
    "suspect": false
  },
  {
    "name": "Mewtwo ex",
    "set": "Destined Rivals",
    "number": "231",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,625 (2025)",
    "rawNM": 558,
    "psa9": 551,
    "psa10": 1426,
    "mult": 2.6,
    "suspect": false
  },
  {
    "name": "Rayquaza V",
    "set": "Evolving Skies",
    "number": "194",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,800 (None)",
    "rawNM": 380,
    "psa9": 495,
    "psa10": 1545,
    "mult": 4.1,
    "suspect": false
  },
  {
    "name": "Espeon ex",
    "set": "Prismatic Evolutions",
    "number": "155",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,599 (2025)",
    "rawNM": 289,
    "psa9": 297,
    "psa10": 1288,
    "mult": 4.5,
    "suspect": false
  },
  {
    "name": "Lugia GX",
    "set": "Lost Thunder",
    "number": "207",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,525 (None)",
    "rawNM": 124,
    "psa9": 183,
    "psa10": 1499,
    "mult": 12.1,
    "suspect": false
  },
  {
    "name": "Espeon ex",
    "set": "BREAKpoint",
    "number": "117/122",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,500 (2016)",
    "rawNM": 66,
    "psa9": 200,
    "psa10": 1295,
    "mult": 19.6,
    "suspect": false
  },
  {
    "name": "Reshiram ex",
    "set": "White Flare",
    "number": "173/86",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,493 (None)",
    "rawNM": 462,
    "psa9": 460,
    "psa10": 1493,
    "mult": 3.2,
    "suspect": false
  },
  {
    "name": "Umbreon ex",
    "set": "Fates Collide",
    "number": "55",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,450 (2016)",
    "rawNM": 45,
    "psa9": 125,
    "psa10": 1600,
    "mult": 35.9,
    "suspect": false
  },
  {
    "name": "Team Rocket's Mewtwo",
    "set": "Destined Rivals",
    "number": "231/182",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Top chase of blockbuster 2025 set, Rocket+Mewtwo demand",
    "rawNM": 562,
    "psa9": 551,
    "psa10": 1426,
    "mult": 2.5,
    "suspect": false
  },
  {
    "name": "Pikachu ex",
    "set": "Prismatic Evolutions",
    "number": "277/217",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,400 (2026)",
    "rawNM": 288,
    "psa9": 312,
    "psa10": 1400,
    "mult": 4.9,
    "suspect": false
  },
  {
    "name": "Espeon ex",
    "set": "Prismatic Evolutions",
    "number": "157/131",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Eeveelution SIR, psychic-type chase, textured",
    "rawNM": 289,
    "psa9": 297,
    "psa10": 1343,
    "mult": 4.6,
    "suspect": false
  },
  {
    "name": "Victini",
    "set": "Black Bolt",
    "number": "171",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,396 (2025)",
    "rawNM": 545,
    "psa9": 590,
    "psa10": 1399,
    "mult": 2.6,
    "suspect": false
  },
  {
    "name": "Dragonite V",
    "set": "Evolving Skies",
    "number": "192/203",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,300 (None)",
    "rawNM": 450,
    "psa9": 500,
    "psa10": 1300,
    "mult": 2.9,
    "suspect": false
  },
  {
    "name": "Victini",
    "set": "White Flare",
    "number": "172/86",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,299 (2025)",
    "rawNM": 500,
    "psa9": 522,
    "psa10": 1299,
    "mult": 2.6,
    "suspect": false
  },
  {
    "name": "Umbreon V",
    "set": "Evolving Skies",
    "number": "189/203",
    "era": "SwSh",
    "tier": "premium",
    "gem": "moderate",
    "why": "Umbreon brand carries it, reliable $500 ceiling",
    "rawNM": 337,
    "psa9": 405,
    "psa10": 1247,
    "mult": 3.7,
    "suspect": false
  },
  {
    "name": "Espeon",
    "set": "Fusion Strike",
    "number": "SWSH174",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,200 (2021)",
    "rawNM": 173,
    "psa9": 199,
    "psa10": 988,
    "mult": 5.7,
    "suspect": false
  },
  {
    "name": "Pikachu ex",
    "set": "Surging Sparks",
    "number": "238/191",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Set king, Pikachu liquidity unmatched. Textured, screen hard",
    "rawNM": 320,
    "psa9": 320,
    "psa10": 1149,
    "mult": 3.6,
    "suspect": false
  },
  {
    "name": "Team Rocket's Mewtwo ex",
    "set": "Ascended Heroes",
    "number": "281",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,300 (2026)",
    "rawNM": 466,
    "psa9": 488,
    "psa10": 1150,
    "mult": 2.5,
    "suspect": false
  },
  {
    "name": "Greninja ex",
    "set": "Twilight Masquerade",
    "number": "214",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $930 (2024)",
    "rawNM": 358,
    "psa9": 355,
    "psa10": 965,
    "mult": 2.7,
    "suspect": false
  },
  {
    "name": "Charizard V",
    "set": "Brilliant Stars",
    "number": "154/172",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,000 (2022)",
    "rawNM": 305,
    "psa9": 348,
    "psa10": 926,
    "mult": 3.0,
    "suspect": false
  },
  {
    "name": "Pikachu & Zekrom GX",
    "set": "Team Up",
    "number": "184",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,000 (2019)",
    "rawNM": 206,
    "psa9": 220,
    "psa10": 821,
    "mult": 4.0,
    "suspect": false
  },
  {
    "name": "Charizard ex",
    "set": "Paldean Fates",
    "number": "234",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,000 (2024)",
    "rawNM": 320,
    "psa9": 318,
    "psa10": 932,
    "mult": 2.9,
    "suspect": false
  },
  {
    "name": "Glaceon ex",
    "set": "Prismatic Evolutions",
    "number": "150/131",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $835 (2025)",
    "rawNM": 262,
    "psa9": 260,
    "psa10": 810,
    "mult": 3.1,
    "suspect": false
  },
  {
    "name": "Leafeon ex",
    "set": "Prismatic Evolutions",
    "number": "144",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $1,000 (2025)",
    "rawNM": 320,
    "psa9": 330,
    "psa10": 936,
    "mult": 2.9,
    "suspect": false
  },
  {
    "name": "Rayquaza GX",
    "set": "Celestial Storm",
    "number": "177/168",
    "era": "XYSM",
    "tier": "high",
    "gem": "tough",
    "why": "Premium ceiling, best $/grade in S&M when you land the 10",
    "rawNM": 261,
    "psa9": 234,
    "psa10": 1000,
    "mult": 3.8,
    "suspect": false
  },
  {
    "name": "Umbreon GX",
    "set": "Hidden Fates",
    "number": "SV69",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $970 (None)",
    "rawNM": 257,
    "psa9": 266,
    "psa10": 970,
    "mult": 3.8,
    "suspect": false
  },
  {
    "name": "Vaporeon ex",
    "set": "Prismatic Evolutions",
    "number": "149",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $960 (2025)",
    "rawNM": 255,
    "psa9": 280,
    "psa10": 972,
    "mult": 3.8,
    "suspect": false
  },
  {
    "name": "Suicune GX",
    "set": "Lost Thunder",
    "number": "220",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $950 (2018)",
    "rawNM": 81,
    "psa9": 110,
    "psa10": 770,
    "mult": 9.5,
    "suspect": false
  },
  {
    "name": "Pikachu",
    "set": "Paldean Fates",
    "number": "131",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $950 (2024)",
    "rawNM": 80,
    "psa9": 108,
    "psa10": 850,
    "mult": 10.7,
    "suspect": false
  },
  {
    "name": "Raichu",
    "set": "Paldea Evolved",
    "number": "211/193",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $900 (2023)",
    "rawNM": 103,
    "psa9": 121,
    "psa10": 867,
    "mult": 8.4,
    "suspect": false
  },
  {
    "name": "Mew ex",
    "set": "Pokemon 151",
    "number": "053",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $914 (2023)",
    "rawNM": 405,
    "psa9": 284,
    "psa10": 1260,
    "mult": 3.1,
    "suspect": false
  },
  {
    "name": "Glaceon ex",
    "set": "Prismatic Evolutions",
    "number": "155/131",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Eeveelution SIR, ice-type fan demand",
    "rawNM": 260,
    "psa9": 264,
    "psa10": 854,
    "mult": 3.3,
    "suspect": false
  },
  {
    "name": "Blaziken VMAX",
    "set": "Chilling Reign",
    "number": "201/198",
    "era": "SwSh",
    "tier": "premium",
    "gem": "moderate",
    "why": "Best Chilling Reign alt art, liquid",
    "rawNM": 340,
    "psa9": 362,
    "psa10": 838,
    "mult": 2.5,
    "suspect": false
  },
  {
    "name": "Oshawott IR",
    "set": "White Flare",
    "number": "105/86",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $875 (None)",
    "rawNM": 81,
    "psa9": 80,
    "psa10": 678,
    "mult": 8.4,
    "suspect": false
  },
  {
    "name": "Pikachu",
    "set": "Lost Origin",
    "number": "TG05",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $560 (None)",
    "rawNM": 58,
    "psa9": 90,
    "psa10": 798,
    "mult": 13.8,
    "suspect": false
  },
  {
    "name": "Espeon VMAX",
    "set": "Fusion Strike",
    "number": "270/264",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $800 (None)",
    "rawNM": 312,
    "psa9": 326,
    "psa10": 800,
    "mult": 2.6,
    "suspect": false
  },
  {
    "name": "Shiny Charizard GX",
    "set": "Hidden Fates Shiny Vault",
    "number": "SV49/SV94",
    "era": "XYSM",
    "tier": "high",
    "gem": "tough",
    "why": "#1 SM chase, bulletproof liquidity, Charizard premium, textured border",
    "rawNM": 454,
    "psa9": 652,
    "psa10": 1275,
    "mult": 2.8,
    "suspect": false
  },
  {
    "name": "Charizard ex",
    "set": "Obsidian Flames",
    "number": "223",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Tera Charizard SIR, ~6.6x multiplier, Charizard liquidity absorbs misses",
    "rawNM": 119,
    "psa9": 160,
    "psa10": 780,
    "mult": 6.5,
    "suspect": false
  },
  {
    "name": "Sylveon VMAX",
    "set": "Evolving Skies",
    "number": "212",
    "era": "SwSh",
    "tier": "premium",
    "gem": "tough",
    "why": "#2 Eeveelution alt, Eevee-line centering issues",
    "rawNM": 384,
    "psa9": 385,
    "psa10": 750,
    "mult": 2.0,
    "suspect": false
  },
  {
    "name": "Sylveon",
    "set": "Prismatic Evolutions",
    "number": "040",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $760 (None)",
    "rawNM": 2,
    "psa9": 29,
    "psa10": 244,
    "mult": 124.1,
    "suspect": true
  },
  {
    "name": "Hoothoot TG",
    "set": "Astral Radiance",
    "number": "TG12",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $750 (None)",
    "rawNM": 8,
    "psa9": 42,
    "psa10": 675,
    "mult": 79.5,
    "suspect": true
  },
  {
    "name": "Roaring Moon ex",
    "set": "Prismatic Evolutions",
    "number": "162",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $750 (2025)",
    "rawNM": 174,
    "psa9": 185,
    "psa10": 763,
    "mult": 4.4,
    "suspect": false
  },
  {
    "name": "Vanilluxe",
    "set": "White Flare",
    "number": "113/86",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $750 (None)",
    "rawNM": 34,
    "psa9": 30,
    "psa10": 262,
    "mult": 7.7,
    "suspect": false
  },
  {
    "name": "Flareon ex",
    "set": "Prismatic Evolutions",
    "number": "146",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $750 (2025)",
    "rawNM": 170,
    "psa9": 205,
    "psa10": 691,
    "mult": 4.1,
    "suspect": false
  },
  {
    "name": "Cynthia ex",
    "set": "Destined Rivals",
    "number": "232/182",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $750 (2025)",
    "rawNM": 262,
    "psa9": 275,
    "psa10": 650,
    "mult": 2.5,
    "suspect": false
  },
  {
    "name": "Jolteon ex",
    "set": "Prismatic Evolutions",
    "number": "153/131",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Eeveelution SIR, electric-type chase",
    "rawNM": 172,
    "psa9": 200,
    "psa10": 650,
    "mult": 3.8,
    "suspect": false
  },
  {
    "name": "Glaceon ex",
    "set": "Fates Collide",
    "number": "116",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $740 (2016)",
    "rawNM": 26,
    "psa9": 83,
    "psa10": 734,
    "mult": 28.7,
    "suspect": false
  },
  {
    "name": "Mega Charizard ex",
    "set": "XY Evolutions",
    "number": "101/108",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $730 (2016)",
    "rawNM": 140,
    "psa9": 180,
    "psa10": 732,
    "mult": 5.2,
    "suspect": false
  },
  {
    "name": "Mew",
    "set": "Crown Zenith",
    "number": "GG10",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $729 (2023)",
    "rawNM": 69,
    "psa9": 97,
    "psa10": 670,
    "mult": 9.7,
    "suspect": false
  },
  {
    "name": "Charizard ex",
    "set": "XY Evolutions",
    "number": "101",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $726 (None)",
    "rawNM": 136,
    "psa9": 175,
    "psa10": 735,
    "mult": 5.4,
    "suspect": false
  },
  {
    "name": "Charizard",
    "set": "Unbroken Bonds",
    "number": "217/214",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $720 (2019)",
    "rawNM": 190,
    "psa9": 214,
    "psa10": 720,
    "mult": 3.8,
    "suspect": false
  },
  {
    "name": "Gardevoir ex",
    "set": "Steam Siege",
    "number": "112/114",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $710 (2016)",
    "rawNM": 55,
    "psa9": 99,
    "psa10": 488,
    "mult": 8.9,
    "suspect": false
  },
  {
    "name": "Mew",
    "set": "Pokemon 151",
    "number": "168",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $705 (2023)",
    "rawNM": 106,
    "psa9": 139,
    "psa10": 685,
    "mult": 6.4,
    "suspect": false
  },
  {
    "name": "Leafeon VMAX",
    "set": "Evolving Skies",
    "number": "205/203",
    "era": "SwSh",
    "tier": "premium",
    "gem": "tough",
    "why": "Mid-tier Eeveelution alt, reliable demand",
    "rawNM": 340,
    "psa9": 350,
    "psa10": 660,
    "mult": 1.9,
    "suspect": false
  },
  {
    "name": "Mewtwo VSTAR",
    "set": "Crown Zenith",
    "number": "GG44",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $700 (2023)",
    "rawNM": 292,
    "psa9": 312,
    "psa10": 680,
    "mult": 2.3,
    "suspect": false
  },
  {
    "name": "Psyduck",
    "set": "Ascended Heroes",
    "number": "226/217",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $700 (None)",
    "rawNM": 105,
    "psa9": 184,
    "psa10": 700,
    "mult": 6.7,
    "suspect": false
  },
  {
    "name": "Gastly",
    "set": "Temporal Forces",
    "number": "177",
    "era": "SV",
    "tier": "premium",
    "gem": "easy",
    "why": "Top IR in set, 45% gem, Gengar-line demand, huge premium",
    "rawNM": 108,
    "psa9": 125,
    "psa10": 654,
    "mult": 6.1,
    "suspect": false
  },
  {
    "name": "Mega Charizard Y ex",
    "set": "Ascended Heroes",
    "number": "294/217",
    "era": "SV",
    "tier": "premium",
    "gem": "tough",
    "why": "Gold Mega Hyper Rare, Charizard premium",
    "rawNM": 622,
    "psa9": 780,
    "psa10": 3233,
    "mult": 5.2,
    "suspect": false
  },
  {
    "name": "Zekrom ex",
    "set": "Black Bolt",
    "number": "174/86",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $677 (2025)",
    "rawNM": 311,
    "psa9": 336,
    "psa10": 736,
    "mult": 2.4,
    "suspect": false
  },
  {
    "name": "Mega Starmie ex",
    "set": "Perfect Order",
    "number": "118",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $675 (2026)",
    "rawNM": 67,
    "psa9": 90,
    "psa10": 474,
    "mult": 7.1,
    "suspect": false
  },
  {
    "name": "BLASTOISE ex",
    "set": "Pokemon 151",
    "number": "200",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $675 (2023)",
    "rawNM": 150,
    "psa9": 178,
    "psa10": 655,
    "mult": 4.4,
    "suspect": false
  },
  {
    "name": "Espeon V",
    "set": "Evolving Skies",
    "number": "195/203",
    "era": "SwSh",
    "tier": "mid",
    "gem": "moderate",
    "why": "Best multiplier on list: ~$70 raw -> ~$675 PSA10",
    "rawNM": 200,
    "psa9": 215,
    "psa10": 635,
    "mult": 3.2,
    "suspect": false
  },
  {
    "name": "Gengar",
    "set": "Lost Origin",
    "number": "TG06",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $650 (None)",
    "rawNM": 58,
    "psa9": 96,
    "psa10": 664,
    "mult": 11.5,
    "suspect": false
  },
  {
    "name": "Eevee ex",
    "set": "Prismatic Evolutions",
    "number": "167/131",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $680 (2025)",
    "rawNM": 180,
    "psa9": 185,
    "psa10": 660,
    "mult": 3.7,
    "suspect": false
  },
  {
    "name": "Pikachu V",
    "set": "Lost Origin",
    "number": "TG16",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $560 (None)",
    "rawNM": 120,
    "psa9": 140,
    "psa10": 520,
    "mult": 4.3,
    "suspect": false
  },
  {
    "name": "Marnie ex",
    "set": "Ascended Heroes",
    "number": "287",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $650 (2026)",
    "rawNM": 80,
    "psa9": 119,
    "psa10": 310,
    "mult": 3.9,
    "suspect": false
  },
  {
    "name": "Shiny Charizard ex",
    "set": "Paldean Fates",
    "number": "234/091",
    "era": "SV",
    "tier": "high",
    "gem": "moderate",
    "why": "44% gem (well above 151 trap), top hobby liquidity, shiny-vault stock grades clean",
    "rawNM": 319,
    "psa9": 318,
    "psa10": 774,
    "mult": 2.4,
    "suspect": false
  },
  {
    "name": "Cynthia's Garchomp ex",
    "set": "Destined Rivals",
    "number": "232/182",
    "era": "SV",
    "tier": "premium",
    "gem": "moderate",
    "why": "Cynthia trainer SIR, strong demand",
    "rawNM": 266,
    "psa9": 275,
    "psa10": 649,
    "mult": 2.4,
    "suspect": false
  },
  {
    "name": "Glaceon VMAX",
    "set": "Evolving Skies",
    "number": "209/203",
    "era": "SwSh",
    "tier": "premium",
    "gem": "tough",
    "why": "Popular Eeveelution alt, centering caveat",
    "rawNM": 280,
    "psa9": 300,
    "psa10": 640,
    "mult": 2.3,
    "suspect": false
  },
  {
    "name": "Mew ex",
    "set": "Pokemon 151",
    "number": "191",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $643 (2025)",
    "rawNM": 199,
    "psa9": 248,
    "psa10": 640,
    "mult": 3.2,
    "suspect": false
  },
  {
    "name": "Mew ex",
    "set": "Pokemon 151",
    "number": "200",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $640 (2023)",
    "rawNM": 149,
    "psa9": 177,
    "psa10": 633,
    "mult": 4.3,
    "suspect": false
  },
  {
    "name": "Charmander",
    "set": "Pokemon 151",
    "number": "168/165",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $635 (2023)",
    "rawNM": 32,
    "psa9": 137,
    "psa10": 635,
    "mult": 19.7,
    "suspect": false
  },
  {
    "name": "Dragonite GX",
    "set": "Unified Minds",
    "number": "248/236",
    "era": "XYSM",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $630 (None)",
    "rawNM": 119,
    "psa9": 134,
    "psa10": 726,
    "mult": 6.1,
    "suspect": false
  },
  {
    "name": "Moltres V",
    "set": "Chilling Reign",
    "number": "177",
    "era": "SwSh",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $630 (2021)",
    "rawNM": 200,
    "psa9": 213,
    "psa10": 564,
    "mult": 2.8,
    "suspect": false
  },
  {
    "name": "Pikachu",
    "set": "Pokemon 151",
    "number": "173",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $625 (2023)",
    "rawNM": 42,
    "psa9": 106,
    "psa10": 600,
    "mult": 14.1,
    "suspect": false
  },
  {
    "name": "Zekrom ex",
    "set": "Black Bolt",
    "number": "166",
    "era": "SV",
    "tier": "premium",
    "gem": "",
    "why": "Real eBay-sold PSA10 $619 (2025)",
    "rawNM": 250,
    "psa9": 256,
    "psa10": 600,
    "mult": 2.4,
    "suspect": false
  }
];

export default GRADING_CARDS;
